CREATE TABLE IF NOT EXISTS "SUPER_HERO" (
  "ID" BIGINT  PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(50) NOT NULL,
  "DESCRIPTION" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "HERO_SUPER_POWER" (
  "ID" BIGINT  PRIMARY KEY AUTO_INCREMENT,
  "SUPERHERO_ID" BIGINT NOT NULL,
  "SUPER_POWER" VARCHAR(50) NOT NULL,
  FOREIGN KEY ("SUPERHERO_ID") REFERENCES "SUPER_HERO"("ID")
);

