package com.w2m.heroestest.model.enums;

import lombok.*;

public enum SuperPower {
    INVISIBILITY,
    PHASING,
    MIND_CONTROL,
    SHAPE_SHIFTING,
    TIME_TRAVEL,
    MOLECULAR_COMBUSTION,
    SUPER_STRENGHT,
    FIRE_CONTROL,
    ELECTROCUTION,
    EXTRAORDINARY_INTELLIGENCE,
    FORCE_FIELDS,
    TELEKINESIS,
    BIOKINESIS,
    X_RAY_VISION,
    PRECOGNITION,
    SUPER_HEALING,
    SELF_REGENERATION,
    FLY

}
